basePath: /api/v1
definitions:
  dto.AppealBody:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      reason:
        type: integer
      theme:
        type: string
    type: object
  dto.EditEmailOrLogin:
    properties:
      new_value:
        type: string
    type: object
  dto.LoginBody:
    properties:
      login_or_email:
        type: string
      password:
        type: string
    type: object
  dto.RegisterBody:
    properties:
      email:
        type: string
      login:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  title: Johny Tuna
  version: "1.0"
paths:
  /appeal:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные обращения
        in: body
        name: appeal_body
        required: true
        schema:
          $ref: '#/definitions/dto.AppealBody'
      produces:
      - application/json
      responses: {}
      summary: Обращение
      tags:
      - appeal
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для входа
        in: body
        name: login_body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginBody'
      produces:
      - application/json
      responses: {}
      summary: Вход в аккаунт
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для регистрации
        in: body
        name: register_body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterBody'
      produces:
      - application/json
      responses: {}
      summary: Регистрация (запрос на верификацию почты)
      tags:
      - auth
  /auth/verify:
    get:
      consumes:
      - application/json
      parameters:
      - description: Данные для регистрации + код
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Регистрация (верификация почты по OTP коду)
      tags:
      - auth
  /auth/verify/user:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Верефикация юзера по токену
      tags:
      - auth
  /categories/get:
    get:
      produces:
      - application/json
      responses: {}
      summary: Получение категорий
      tags:
      - categories
  /products/getByCategory:
    get:
      parameters:
      - description: id категории
        in: query
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Получение продуктов по категории
      tags:
      - products
  /profile/info:
    get:
      consumes:
      - application/json
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Получение информации о профиле
      tags:
      - profile
  /profile/update/email:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Новое значение
        in: body
        name: login_body
        required: true
        schema:
          $ref: '#/definitions/dto.EditEmailOrLogin'
      produces:
      - application/json
      responses: {}
      summary: Обновление почты
      tags:
      - profile
  /profile/update/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Новое значение
        in: body
        name: login_body
        required: true
        schema:
          $ref: '#/definitions/dto.EditEmailOrLogin'
      produces:
      - application/json
      responses: {}
      summary: Обновление логина
      tags:
      - profile
  /search/products:
    get:
      parameters:
      - description: Имя продукта (поиск)
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Получение продуктов из поиска
      tags:
      - search
swagger: "2.0"
