basePath: /api/v1
definitions:
  dto.LoginBody:
    properties:
      login_or_email:
        type: string
      password:
        type: string
    type: object
  dto.RegisterBody:
    properties:
      email:
        type: string
      login:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  title: Johny Tuna
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для входа
        in: body
        name: login_body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginBody'
      produces:
      - application/json
      responses: {}
      summary: Вход в аккаунт
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для регистрации
        in: body
        name: register_body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterBody'
      produces:
      - application/json
      responses: {}
      summary: Регистрация
      tags:
      - auth
  /categories/get:
    get:
      produces:
      - application/json
      responses: {}
      summary: Получение категорий
      tags:
      - categories
  /products/getByCategory:
    get:
      parameters:
      - description: id категории
        in: query
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Получение продуктов по категории
      tags:
      - products
  /search/products:
    get:
      parameters:
      - description: Имя продукта (поиск)
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Получение продуктов из поиска
      tags:
      - search
swagger: "2.0"
